---
parameters:
  - name: action
    type: string
    values:
      - Default
      - DryRun
  - name: gitUserEmail
    type: string
  - name: gitUserName
    type: string
  - name: nextEnvironment
    type: string
    default: ""
  - name: organisationName
    type: string
  - name: rangerVersion
    type: string

resources:
  repositories:
    - repository: self

jobs:
  - job: Execute
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InstallRangerCLI@0
        inputs:
          version: ${{ parameters.rangerVersion }}
      - task: DeploySet@0
        inputs:
          gitUserEmail: ${{ parameters.gitUserEmail }}
          gitUserName: ${{ parameters.gitUserName }}
          organisationName: frontierdigital
          pat: $(System.AccessToken)
          projectName: $(System.TeamProject)
      - ${{ if parameters.nextEnvironment }}:
          - task: PromoteSet@0
            inputs:
              gitUserEmail: ${{ parameters.gitUserEmail }}
              gitUserName: ${{ parameters.gitUserName }}
              nextEnvironment: ${{ parameters.nextEnvironment }}
              organisationName: ${{ parameters.organisationName }}
              pat: $(System.AccessToken)
              projectName: $(System.TeamProject)
