---
parameters:
  - name: configRef
    type: string
  - name: deploySteps
    type: stepList
    default: []
  - name: environmentName
    type: string
  - name: installSteps
    type: stepList
    default: []
  - name: organisationName
    type: string
  - name: serviceConnectionName
    type: string
  - name: workloadFeedName
    type: string

resources:
  repositories:
    - repository: self

stages:
  - template: ../stages/deploy.yml
    parameters:
      configRef: ${{ parameters.configRef }}
      deploySteps: ${{ parameters.deploySteps }}
      environmentName: ${{ parameters.environmentName }}
      installSteps: ${{ parameters.installSteps }}
      organisationName: ${{ parameters.organisationName }}
      serviceConnectionName: ${{ parameters.serviceConnectionName }}
      workloadFeedName: ${{ parameters.workloadFeedName }}
