---
parameters:
  - name: action
    type: string
    values:
      - Default
      - Publish
  - name: buildSteps
    type: stepList
    default: []
  - name: gitUserEmail
    type: string
  - name: gitUserName
    type: string
  - name: installSteps
    type: stepList
    default: []
  - name: organisationName
    type: string
  - name: postPublishSteps
    type: stepList
    default: []
  - name: prePublishSteps
    type: stepList
    default: []
  - name: testSteps
    type: stepList
    default: []
  - name: workloadFeedName
    type: string

resources:
  repositories:
    - repository: self

stages:
  - template: ../stages/build.yml
    parameters:
      buildSteps: ${{ parameters.buildSteps }}
      gitUserEmail: ${{ parameters.gitUserEmail }}
      gitUserName: ${{ parameters.gitUserName }}
      installSteps: ${{ parameters.installSteps }}
      organisationName: ${{ parameters.organisationName }}
      postPublishSteps: ${{ parameters.postPublishSteps }}
      prePublishSteps: ${{ parameters.prePublishSteps }}
      testSteps: ${{ parameters.testSteps }}
  - template: ../stages/publish.yml
    parameters:
      condition: |
        and(
          succeeded(),
          or(
            eq(variables['build.sourceBranch'], 'refs/heads/main'),
            eq('${{ parameters.action }}', 'Publish')
          )
        )
      jobs:
        - template: ../jobs/publish-workload-package.yml
          parameters:
            workloadFeedName: ${{ parameters.workloadFeedName }}
