---
parameters:
  - name: configRef
    type: string
  - name: deploySteps
    type: stepList
    default: []
  - name: environment
    type: string
  - name: organisationName
    type: string
  - name: serviceConnectionName
    type: string
  - name: set
    type: string
  - name: workloadName
    type: string

resources:
  repositories:
    - repository: self

stages:
  - template: ../stages/deploy.yml
    parameters:
      configRef: ${{ parameters.configRef }}
      deploySteps: ${{ parameters.deploySteps }}
      environment: ${{ parameters.environment }}
      organisationName: ${{ parameters.organisationName }}
      serviceConnectionName: ${{ parameters.serviceConnectionName }}
      set: ${{ parameters.set }}
      workloadName: ${{ parameters.workloadName }}
