---
parameters:
  - name: buildSteps
    type: stepList
    default: []
  - name: gitUserEmail
    type: string
  - name: gitUserName
    type: string
  - name: organisationName
    type: string
  - name: postPublishSteps
    type: stepList
    default: []
  - name: prePublishSteps
    type: stepList
    default: []
  - name: setupSteps
    type: stepList
    default: []
  - name: testSteps
    type: stepList
    default: []

stages:
  - stage: Build
    pool:
      vmImage: ubuntu-latest
    jobs:
      - template: ../jobs/preflight.yml
      - job: Build
        dependsOn: Preflight
        variables:
          - name: versionFromFile
            value: $[dependencies.Preflight.outputs['getVersionFromFile.versionFromFile']]
          - name: versionLabel
            ${{ if or(eq(variables['Build.SourceBranchName'], 'main'), eq(variables['Build.SourceBranchName'], 'master')) }}:
              value: ""
            ${{ if and(ne(variables['Build.SourceBranchName'], 'main'), ne(variables['Build.SourceBranchName'], 'master')) }}:
              value: "-unstable"
          - name: pipelineCounter
            value: $[counter(dependencies.Preflight.outputs['getVersionFromFile.versionFromFile'], 0)]
        steps:
          - checkout: self
            submodules: true
          - template: ../steps/configure-git-authentication.yml
            parameters:
              organisationName: ${{ parameters.organisationName }}
              pat: $(System.AccessToken)
          - template: ../steps/configure-git-user.yml
            parameters:
              gitUserEmail: ${{ parameters.gitUserEmail }}
              gitUserName: ${{ parameters.gitUserName }}
          - template: ../steps/set-version-variable.yml
            parameters:
              pipelineCounter: $(pipelineCounter)
              versionFromFile: $(versionFromFile)
              versionLabel: $(versionLabel)
          - template: ../steps/add-tag.yml
            parameters:
              force: true # TODO: Remove
              tag: $(version)
          - template: ../steps/update-version-file.yml
            parameters:
              version: $(version)
          - ${{ parameters.setupSteps }}
          - ${{ parameters.buildSteps }}
          - ${{ parameters.testSteps }}
          - ${{ parameters.prePublishSteps }}
          - template: ../steps/publish-pipeline-artifact.yml
          - ${{ parameters.postPublishSteps }}
          - template: ../steps/clear-agent-build-directory.yml
            condition: always()
