---
parameters:
  - name: condition
    type: string
  - name: jobs
    type: jobList

stages:
  - stage: Publish
    pool:
      vmImage: ubuntu-latest
    condition: ${{ parameters.condition }}
    jobs:
      - ${{ parameters.jobs }}
