---
parameters:
  - name: gitAuthorEmail
    type: string
  - name: gitAuthorName
    type: string

steps:
  - script: |
      git config --local user.email "${{ parameters.gitAuthorEmail }}"
      git config --local user.name "${{ parameters.gitAuthorName }}"
    displayName: Configure git author
