---
parameters:
  - name: gitUserEmail
    type: string
  - name: gitUserName
    type: string

steps:
  - script: |
      git config --local user.email "${{ parameters.gitUserEmail }}"
      git config --local user.name "${{ parameters.gitUserName }}"
    displayName: Configure git author
