---
parameters:
  - name: organisationName
    type: string
  - name: ref
    type: string
  - name: serviceConnectionName
    type: string

steps:
  - bash: |
      set -euo pipefail

      PROJECT_NAME="$(echo ${{ parameters.ref }} | cut -d "/" -f 1)"
      REPOSITORY_NAME="$(echo ${{ parameters.ref }} | cut -d "/" -f 2 | cut -d "@" -f 1)"
      SHA="$(echo ${{ parameters.ref }} | cut -d "/" -f 2 | cut -d "@" -f 2)"

      pushd $(Agent.TempDirectory) 1> /dev/null
      git clone "https://${{ parameters.organisationName }}@dev.azure.com/${{ parameters.organisationName }}/${PROJECT_NAME}/_git/${REPOSITORY_NAME}"
      pushd $REPOSITORY_NAME 1> /dev/null
      git -c advice.detachedHead=false checkout $SHA
      git show -s --format=%h
      popd 1> /dev/null
      popd 1> /dev/null

      CONFIG_DIR_PATH="$(Agent.TempDirectory)/${REPOSITORY_NAME}"
      echo "##vso[task.setvariable variable=configDirPath]$CONFIG_DIR_PATH"
    displayName: Clone config repository
  - bash: if [ -d "$(configDirPath)/.config" ]; then cp -r "$(configDirPath)/.config" $(System.DefaultWorkingDirectory)/.config; fi
    displayName: Fetch config
  - task: AzureCLI@2
    displayName: Fetch secrets
    inputs:
      azureSubscription: ${{ parameters.serviceConnectionName }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -euo pipefail

        if [ -d "$(configDirPath)/.secrets" ]; then
          cp -r "$(configDirPath)/.secrets" $(System.DefaultWorkingDirectory)/.secrets

          wget --quiet -O $(System.DefaultWorkingDirectory)/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          chmod +x $(System.DefaultWorkingDirectory)/sops

          find $(System.DefaultWorkingDirectory)/.secrets -type f -print0 | xargs -0 -I % sh -c 'echo "Decrypting %" && $(System.DefaultWorkingDirectory)/sops --decrypt --in-place %'
        fi
